[tool.poetry]
name = "image-segmentation-app"
version = "0.1.0"
description = ""
authors = ["daisuke"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.101.1"
uvicorn = "^0.23.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
